app/urls.py
from django.urls import path
from app.views import *

app_name = 'app'

urlpatterns = [
	path('', index, name='index'),
	path('pila/nueva', PilaCreate.as_view(), name='pila-nueva'),
	path('pila/<int:pk>/eliminar', PilaDelete.as_view(), name='pila-delete'),
	path('pila/<int:pk>/editar', PilaUpdate.as_view(), name='pila-update'),
	path('materia-prima/agregar', MateriaPrimaCreate.as_view(), name='materia-prima-nueva'),
	path('predio/agregar', PredioCreate.as_view(), name='predio-nuevo'),

	path('registros', RegistrosView.as_view(), name='registros'),
	path('registros/<int:pk>', medicionesPila, name='mediciones-pila'),

	path('chart/<int:pk>', chart, name='chart'),
	path('chart', allCharts, name='all-charts'),

	path('reporte/<int:pk>', pdf_test, name='pdf'),

]

appremoto/urls.py
from appremoto.views import clienteIndex, predios, home
from django.urls import path
from app.views import *

app_name = 'appremoto'

urlpatterns = [
    path('index/', clienteIndex, name='clienteIndex'),
    path('predios/<int:pk>', predios, name='predios'),
    path('', home, name='home')
]

remoto/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView
from rest_framework import routers
from app import views
#rest jwt
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
    TokenVerifyView,
)


admin.site.site_header = 'Gestión de datos y administación de usuarios SFPC'

router = routers.DefaultRouter()
router.register('users', views.UserViewSet)
router.register('groups', views.GroupViewSet)
router.register('clientes', views.ClienteViewSet)
router.register('usuarios', views.CuentaUsuarioViewSet)
router.register('lanzas', views.LanzaViewSet)
router.register('pilas', views.PilaViewSet)
router.register('registros', views.MedicionViewSet)
router.register('materias-primas', views.MateriaPrimaViewSet)
router.register('predios', views.PredioViewSet)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app/', include('app.urls', namespace='app')),
    path('appremoto/', include('appremoto.urls', namespace='appremoto')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', RedirectView.as_view(url='/accounts/login/', permanent=True)),
    path('', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('api/token/verify/', TokenVerifyView.as_view(), name='token_verify'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/models.py
from django.db import models
from django.contrib.auth.models import User

class Cliente(models.Model):
    """ Empresa o agricultor que compra la lanza"""
    #id automatico con autoincremento
    nombre = models.CharField(max_length=200, default="")
    rut = models.CharField(max_length=9)
    direccion = models.CharField(max_length=200, default="")
    email = models.EmailField(unique=True)
    telefono = models.CharField(max_length=15, default="")
    fecha_creacion = models.DateTimeField("fecha de creación", auto_now_add=True)

    def __str__(self):
        if self.nombre:
            return self.nombre
        return self.rut

    class Meta:
        ordering = ('nombre', )

class CuentaUsuario(models.Model):
    usuario = models.OneToOneField(User, on_delete=models.CASCADE)
    cliente = models.ForeignKey('Cliente', on_delete=models.CASCADE)

    def __str__(self):
        return self.usuario.username + " de " + self.cliente.nombre
    
    class Meta:
        ordering = ('usuario',)
        verbose_name_plural = "Cuentas de Usuario"
    


class Lanza(models.Model):
    """Instrumento de medición"""
    codigo = models.CharField(max_length=100, unique=True, null=False)
    numero_serie = models.CharField("numero de serie", max_length=100, unique=True, null=False)
    modelo = models.CharField(max_length=20, default="")
    cliente = models.ForeignKey('Cliente', on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return f"{self.codigo} - {self.cliente.nombre}"

class Pila(models.Model):
    """Pila"""
    nombreID = models.CharField(max_length=10, default=None)
    fecha_creacion = models.DateTimeField("fecha de creación", auto_now_add=True)
    cliente = models.ForeignKey('Cliente', on_delete=models.DO_NOTHING, null=True)
    posicion = models.CharField(max_length=20, null=True) #solo para prubas
    predio = models.ForeignKey('Predio', on_delete=models.SET_NULL, null=True)
    visitado = models.BooleanField(default=False)

    def __str__(self):
    	return f"{self.nombreID} - {self.cliente.nombre}"

    def estado_actual(self):
        temps = self.medicion_set.values_list('temperatura', flat=True)
        if temps:
            if len(list(filter(lambda i:i<=45, temps))) > 1:
                return "Fase I: mesófila"
            elif len(list(filter(lambda i:i>45, temps))) > 7:
                return 'Fase II: termófila'
            elif len(list(filter(lambda i:i<=45, temps))) >= 28:
                return 'Fase III: enfriamiento'
            elif len(temps) >= 35 and len(list(filter(lambda i:i<=45, temps))) >= 28:
                return 'Fase IV: maduración'
            else:
                return "indeterminado"
        else:
            return "Pila sin registros"

    class Meta:
        ordering = ('cliente', )

class Medicion(models.Model):
    """Datos que son medidos por la lanza"""
    fecha_creacion = models.DateTimeField("fecha de creacion", auto_now_add=True)
    temperatura = models.IntegerField(default=0)
    humedad = models.IntegerField(null=True)
    foto = models.ImageField(upload_to='Fotos', null=True, blank=True) #folder Fotos
    lanza = models.ForeignKey('Lanza', on_delete=models.DO_NOTHING)
    pila = models.ForeignKey('Pila', on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.fecha_creacion.strftime("%d-%m-%Y")
    
    class Meta:
        verbose_name_plural = 'Mediciones'
        ordering = ('fecha_creacion', )

class MateriaPrima(models.Model):
    """Materias primas utilizadas en el compost"""
    nombre = models.CharField(max_length=100, null=False)
    cantidad = models.IntegerField(null=False)
    unidad_medida = models.CharField(max_length=10, null=True)
    pila = models.ForeignKey('Pila', on_delete=models.CASCADE)

    def __str__(self):
        return self.nombre

    class Meta:
        verbose_name_plural = 'Materias Primas'
        ordering = ('nombre', )

class Predio(models.Model):
    """Toda pila pertenece a un predio"""
    nombre = models.CharField(max_length=100)
    cliente = models.ForeignKey('Cliente', on_delete=models.DO_NOTHING, null=True)
    def __str__(self):
        return self.nombre

appremoto/models.py
from django.db import models

# Create your models here.

appremoto/views.py
from django.shortcuts import render
from app.models import *
from django.contrib.auth.decorators import login_required, user_passes_test

def es_fiscal(user):
    return user.groups.filter(name='Fiscalizador').exists()

@login_required
@user_passes_test(es_fiscal)
def clienteIndex(request):
    clientes = Cliente.objects.all()
    context = {
        'clientes': clientes,
    }

    return render(request, 'appremoto/fiscal_index.html', context)

@login_required
@user_passes_test(es_fiscal)
def predios(request, pk):
    cliente = Cliente.objects.get(id=pk)
    predios = Predio.objects.filter(cliente_id=pk)
    predios = list(predios)
    pilas = Pila.objects.filter(cliente_id=pk)
    context = {
        'predios': predios,
        'cliente': cliente,
        'pilas': pilas,
    }

    return render(request, 'appremoto/predios_cliente.html', context)

@login_required
def home(request):
    return render(request, 'appremoto/welcome.html' )
    

appremoto/templates/appremoto/fiscal_index.html
{% extends 'base_generic.html' %}

{% block title%}
    Inicio Fiscalización
{% endblock %}

{% block page_content %}
    <div class="fondo-blanco">
        <br>
        <h3 style="text-align: center;">Clientes</h3>

        <table id="tableIndex" class="table table-hover">
        <caption>Lista de clientes</caption>
            <thead>
            <tr>
                <th scope="col">Nombre</th>
                <th scope="col">RUT</th>
                <th scope="col">Dirección</th>
                <th scope="col">Teléfono</th>
                <th scope="col">Email</th>
                <th scope="col">Predios</th>
                <th scope="col">Pilas</th>
            </tr>
            </thead>
            <tbody>
                {% for cliente in clientes %}
                <tr onclick="window.location='{% url 'appremoto:predios' cliente.id %}';"> 
                    <td>{{ cliente.nombre }}</td>
                    <td>{{ cliente.rut }}</td>
                    <td>{{ cliente.direccion }}</td>
                    <td>{{ cliente.telefono }}</td>
                    <td>{{ cliente.email }}</td>
                    <td>{{ cliente.predio_set.all|length }}</td>
                    <td>{{ cliente.pila_set.all|length }}</td>
                
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>

    


{% endblock page_content %}

appremoto/templates/appremoto/predios_cliente.html
{% extends 'base_generic.html' %}

{% block title%}
    Predios por cliente
{% endblock %}

{% block page_content %}
    <br>
    <h3>Predios de {{cliente.nombre}}</h3>

    <div class="accordion" id="accordionExample">
        {% for predio in predios %}
        <div class="accordion-item">
            <h2 class="accordion-header" id="heading{{predio.id}}">
                <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#predio{{predio.id}}" aria-expanded="false" aria-controls="predio{{predio.id}}">
                    {{predio}}
                </button>
            </h2>
            <div id="predio{{predio.id}}" class="accordion-collapse collapse" aria-labelledby="heading{{predio.id}}" data-bs-parent="#accordionExample">
                <div class="accordion-body">
                    {% if pilas %}
                    <table class="table table-borderless table-hover">
                        <thead>
                        <tr>
                            <th scope="col">Pila</th>
                            <th scope="col">Fecha de creación</th>
                            <th scope="col">Estado</th>
                            <th scope="col">Visitado</th>
                        </tr>
                        </thead>
                        <tbody>
                            {%for pila in pilas%}
                                {% if pila.predio.nombre == predio.nombre %}
                                    <tr onclick="window.location='{% url 'app:mediciones-pila' pila.id %}';">
                                        <td>{{ pila.nombreID }}</td>
                                        <td>{{pila.fecha_creacion}}</td>
                                        <td>{{pila.estado_actual}}</td>
                                        <td>
                                            {% if pila.visitado %}
                                                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" style="color:green" fill="currentColor" class="bi bi-check2-square" viewBox="0 0 16 16">
                                                    <path d="M3 14.5A1.5 1.5 0 0 1 1.5 13V3A1.5 1.5 0 0 1 3 1.5h8a.5.5 0 0 1 0 1H3a.5.5 0 0 0-.5.5v10a.5.5 0 0 0 .5.5h10a.5.5 0 0 0 .5-.5V8a.5.5 0 0 1 1 0v5a1.5 1.5 0 0 1-1.5 1.5H3z"/>
                                                    <path d="m8.354 10.354 7-7a.5.5 0 0 0-.708-.708L8 9.293 5.354 6.646a.5.5 0 1 0-.708.708l3 3a.5.5 0 0 0 .708 0z"/>
                                                </svg>
                                            {% else %}
                                                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" style="color:red" fill="currentColor" class="bi bi-x-square" viewBox="0 0 16 16">
                                                    <path d="M14 1a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1h12zM2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2z"/>
                                                    <path d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708z"/>
                                                </svg>
                                            {% endif %}
                                        </td>
                                    </tr>
                                {% endif %}
                            {%endfor%}
                        </tbody>
                    </table>
                    {% else %}
                    <h4>Predio sin pilas</h4>
                    {% endif %}

                </div>
            </div>
        </div>
        {% empty %}
        <div class="alert alert-warning" role="alert">
        <h5>No existen predios/pilas registradas</h5>
        </div>
        
        {% endfor %}
</div>
{% endblock page_content %}

appremoto/templates/appremoto/welcome.html
{% extends 'base_generic.html' %}

{% block title %}
    Bienvenido
{% endblock title %}
{% block content_class %}{% endblock content_class %}
{% block page_content %}
    <h3 style="text-align: center;"> BIENVENIDO </h3>
{% endblock page_content %}