app/urls.py
from django.urls import path
from app.views import *

app_name = 'app'

urlpatterns = [
	path('', index, name='index'),
	path('pila/nueva', PilaCreate.as_view(), name='pila-nueva'),
	path('pila/<int:pk>/eliminar', PilaDelete.as_view(), name='pila-delete'),
	path('pila/<int:pk>/editar', PilaUpdate.as_view(), name='pila-update'),
	path('materia-prima/agregar', MateriaPrimaCreate.as_view(), name='materia-prima-nueva'),
	path('predio/agregar', PredioCreate.as_view(), name='predio-nuevo'),

	path('registros', RegistrosView.as_view(), name='registros'),
	path('registros/<int:pk>', medicionesPila, name='mediciones-pila'),

	path('chart/<int:pk>', chart, name='chart'),
	path('chart', allCharts, name='all-charts'),

	path('reporte/<int:pk>', pdf_test, name='pdf'),

]

appremoto/urls.py
from appremoto.views import clienteIndex, predios, home
from django.urls import path
from app.views import *

app_name = 'appremoto'

urlpatterns = [
    path('index/', clienteIndex, name='clienteIndex'),
    path('predios/<int:pk>', predios, name='predios'),
    path('', home, name='home')
]

remoto/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView
from rest_framework import routers
from app import views
#rest jwt
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
    TokenVerifyView,
)


admin.site.site_header = 'Gestión de datos y administación de usuarios SFPC'

router = routers.DefaultRouter()
router.register('users', views.UserViewSet)
router.register('groups', views.GroupViewSet)
router.register('clientes', views.ClienteViewSet)
router.register('usuarios', views.CuentaUsuarioViewSet)
router.register('lanzas', views.LanzaViewSet)
router.register('pilas', views.PilaViewSet)
router.register('registros', views.MedicionViewSet)
router.register('materias-primas', views.MateriaPrimaViewSet)
router.register('predios', views.PredioViewSet)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app/', include('app.urls', namespace='app')),
    path('appremoto/', include('appremoto.urls', namespace='appremoto')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', RedirectView.as_view(url='/accounts/login/', permanent=True)),
    path('', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('api/token/verify/', TokenVerifyView.as_view(), name='token_verify'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base_generic.html
<!DOCTYPE html>
<html lang="es">
  <head>    
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>
      {% block title %}
      {% endblock %}
    </title>
    {% load static %}
    {% load filter_group %}  
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.24/css/jquery.dataTables.css">
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.24/js/jquery.dataTables.js"></script>

    <link rel="stylesheet" href="{% static '/css/styles.css' %}" >
    <script src="{% static '/js/Chart.js' %}"></script>
    <script src="{% static '/js/scripts.js' %}"></script>

     
  </head>
  <body class="{% block body_class %}body-background{% endblock %}">
    {% block navbar %}
    {% if user.is_authenticated %}
      <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #e3f2fd;">
        <div class="container">
        {% if user|has_group:'Administrador' or user|has_group:'Fiscalizador'%}
          <a class="navbar-brand" href="{% url 'appremoto:clienteIndex' %}">SFPC</a>
        {% elif user|has_group:'Cliente' %}
          <a class="navbar-brand" href="{% url 'app:index' %}">Inicio</a>
        {% endif %}
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          
          <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <ul class="navbar-nav mr-auto">
              {% if user|has_group:'Cliente' %}
              <li class="nav-item">
                <a class="nav-link" href="/app/registros">Registros</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'app:all-charts' %}">Grafico</a>
              </li>
              {% endif %}
              {% if user|has_group:'Administrador' %}
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown"  aria-expanded="true">
                  Administración
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <a class="dropdown-item" href="/admin/app">Datos</a>
                  <a class="dropdown-item" href="/admin/auth">Usuarios</a>
                  <!--<div class="dropdown-divider"></div>
                  <a class="dropdown-item" href="#">Something else here</a>-->
                </div>
              </li>
              {% endif %}
              
            </ul>
          </div>
          
        </div>
        {% if user.is_authenticated%}
          {% if user|has_group:'Administrador' %}
            <span class="navbar-text">Administrador: {{ user.get_username }}</span>
          {% elif user|has_group:'Cliente'%}
            <span class="navbar-text">Cliente: {{ user.get_username }}</span>
          {% elif user|has_group:'Fiscalizador'%}
            <span class="navbar-text">Fiscalizador: {{ user.get_username }}</span>
          {% endif %}
          <a class="nav-link" href="{% url 'logout'%}">Cerrar sesión</a>
        {% else %}
          <a class="nav-link" href="{% url 'login'%}">Iniciar sesión</a>
        {% endif %} 
      </nav>
      {%endif%}
    {% endblock %}
    
    {% block content %}
      <div class="{% block content_class %}fondo-blanco{% endblock content_class %} container">
        {% block page_content %}
        {% endblock %}
      </div>
    {% endblock %}
    <br>
    {% if user.is_authenticated%}
      <footer class="footer">
          <p class="text-center">
              Sistema de Fiscalización de Procesos de Compostaje. Autor: Francisco Flores
              <a href="mailto:ffloresm@udec.cl">ffloresm@udec.cl</a>
          </p>
      </footer>
    {% endif %}
  </body>
</html>