app/urls.py
from django.urls import path
from app.views import *

app_name = 'app'

urlpatterns = [
	path('', index, name='index'),
	path('pila/nueva', PilaCreate.as_view(), name='pila-nueva'),
	path('pila/<int:pk>/eliminar', PilaDelete.as_view(), name='pila-delete'),
	path('pila/<int:pk>/editar', PilaUpdate.as_view(), name='pila-update'),
	path('materia-prima/agregar', MateriaPrimaCreate.as_view(), name='materia-prima-nueva'),
	path('predio/agregar', PredioCreate.as_view(), name='predio-nuevo'),

	path('registros', RegistrosView.as_view(), name='registros'),
	path('registros/<int:pk>', medicionesPila, name='mediciones-pila'),

	path('chart/<int:pk>', chart, name='chart'),
	path('chart', allCharts, name='all-charts'),

	path('reporte/<int:pk>', pdf_test, name='pdf'),

]

remoto/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView
from rest_framework import routers
from app import views
#rest jwt
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
    TokenVerifyView,
)


admin.site.site_header = 'Gestión de datos y administación de usuarios SFPC'

router = routers.DefaultRouter()
router.register('users', views.UserViewSet)
router.register('groups', views.GroupViewSet)
router.register('clientes', views.ClienteViewSet)
router.register('usuarios', views.CuentaUsuarioViewSet)
router.register('lanzas', views.LanzaViewSet)
router.register('pilas', views.PilaViewSet)
router.register('registros', views.MedicionViewSet)
router.register('materias-primas', views.MateriaPrimaViewSet)
router.register('predios', views.PredioViewSet)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app/', include('app.urls', namespace='app')),
    path('appremoto/', include('appremoto.urls', namespace='appremoto')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', RedirectView.as_view(url='/accounts/login/', permanent=True)),
    path('', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('api/token/verify/', TokenVerifyView.as_view(), name='token_verify'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/templates/app/base.html
<!DOCTYPE html>
<html lang="es">
  <head>    
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>
      {% block title %}
      {% endblock %}
    </title>
    {% load static %}  
    <link rel="stylesheet" href="{% static '/css/bootstrap.min.css' %}" >
    <script src="{% static '/js/bootstrap.min.js' %}"></script>
    <script src="{% static '/js/jquery-3.5.1.js' %}"></script>
    <script src="{% static '/js/Chart.js' %}"></script>

     
  </head>
  <body>
    {% block navbar %}
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="{% url 'app:index' %}">Inicio</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
              <a class="nav-link" href="/app/registros">Registros</a>
              <a class="nav-link" href="{% url 'app:all-charts' %}">Grafico</a>
              
            </div>
          </div>
        </div>
      </nav>
    {% endblock %}

    {% block content %}
      <div class="container">
        {% block page_content %}
        {% endblock %}
      </div>
    {% endblock %}
    <br>
  </body>
</html>

app/templates/app/chart.html
{% extends "base_generic.html" %}

{% block title %}
	GRAFICOS
{% endblock %}

{% block page_content %}
    <br>
    <h4 class="text-center">Gráficos de Registros</h4>
    <canvas class="fondo-blanco" id="myChart" width="400" height="200"></canvas>
<script>
var ctx = document.getElementById('myChart').getContext('2d');
var myChart = new Chart(ctx, {
    type: 'line',
    data: {
        labels: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15],
        datasets: [
            {% for k,v in temps.items  %}
            {
                label: "{{ k }}",
                data: {{ v }},
                borderColor: "rgb(255,0,0)",
                fill: false,
                lineTension: 0
            },
            {% endfor %}
            {
                label: "55°C",
                borderColor: "rgb(0,0,0)",
                data: {{ FF }},
                borderDash: [5, 5],
                fill: false,
                lineTension: 0,
                radius: 0
            }
        ]
    },
    options: {
        title: {
            display: true,
            text: 'Evolución de Temperatura y Humedad'
        },
        scales: {
            xAxes: [{
                display: true,
                scaleLabel: {
                    display: true,
                    labelString: 'días'
                }
            }],
            yAxes: [{
                display: true,
                position: 'left',
                scaleLabel: {
                    display: true,
                    labelString: 'temperatura (°C)',
                },
                ticks: {
                    max: 80,
                    min: 0,
                    stepSize: 10
                }
            }]
        }
    }
});
</script>

{% endblock %}

app/templates/app/chart_pila.html
{% extends "base_generic.html" %}

{% block title %}
	GRAFICO PILA {{ pila.nombre.ID}}
{% endblock %}

{% block page_content %}
<br>
<h4 class="text-center">Temperaturas Pila {{pila.nombreID}}</h4>
<canvas id="temp" width="400" height="200"></canvas>

<h4 class="text-center">Humedad Pila {{pila.nombreID}}</h4>
<canvas id="hum" width="400" height="200"></canvas>
<script>
var ctx = document.getElementById('temp').getContext('2d');
var ctx1 = document.getElementById('hum').getContext('2d');
var tempChart = new Chart(ctx, {
    type: 'line',
    data: {
        labels: {{ dias }},
        datasets: [{
            label: 'Temperatura',
            data: {{ temps }},
            borderColor: "rgb(255,0,0)",
            fill: false,
            lineTension: 0
        },
        {
            label: "55°C",
            borderColor: "rgb(0,0,0)",
            data: {{ FF }},
            borderDash: [5, 5],
            fill: false,
            lineTension: 0,
            radius: 0
        }]
    },
    options: {
        title: {
            display: true,
            text: 'Evolución de Temperatura'
        },
        scales: {
            xAxes: [{
                display: true,
                scaleLabel: {
                    display: true,
                    labelString: 'días'
                }
            }],
            yAxes: [{
                display: true,
                position: 'left',
                scaleLabel: {
                    display: true,
                    labelString: 'Temperatura (°C)',
                },
                ticks: {
                    beginAtZero: true
                }
            }]
        }
    }
});
var humChart = new Chart(ctx1, {
    type: 'line',
    data: {
        labels: {{ dias }},
        datasets: [{
            label: "Humedad",
            borderColor: "rgb(0,0,255)",
            data: {{ humedad }},
            fill: false,
            lineTension: 0
        }]
    },
    options: {
        title: {
            display: true,
            text: 'Evolución de Humedad'
        },
        scales: {
            xAxes: [{
                display: true,
                scaleLabel: {
                    display: true,
                    labelString: 'días'
                }
            }],
            yAxes: [{
                //type: 'linear', // only linear but allow scale type registration. This allows extensions to exist solely for log scale for instance
                display: true,
                position: 'left',
                scaleLabel: {
                    display: true,
                    labelString: 'Humedad (%)',
                },
                ticks: {
                    max: 100,
                    min: 0,
                    stepSize: 10
                },
                id: 'y-axis-1'
			}]
        }
    }
});
</script>

{% endblock %}

app/templates/app/index.html
{% extends 'base_generic.html' %}

{% block title %}
	Composite App Data
{% endblock %}

{% block page_content %}
<br>
<div class="page-header">
	<div class="row">
		<div class="col-sm-6">
			<div class="card">
			 	<div class="card-body">
			    	<h3 class="card-title"><b>Datos Cliente</b></h3>
			  	</div>
			  	<ul class="list-group list-group-flush">
			    	<li class="list-group-item">Nombre: <br>
			    		{{ cliente.nombre }}</li>
			    	<li class="list-group-item">Email: <br>
			    		{{ cliente.email }}</li>
			    	<li class="list-group-item">Dirección: <br>
			    		{{ cliente.direccion }}</li>
			  	</ul>
			  	<div class="card-body">
			    	<a href="#" class="card-link">Mi empresa</a>
		  		</div>
			</div>
		</div>
		<div class="col-sm-6">
			<div class="card">
		  		<div class="card-body">
		    		<h3 class="card-title"><b>Datos Lanza</b></h3>
		  		</div>
		  		<ul class="list-group list-group-flush">
		  			{% for lanza in lanzas %}
		    		<li class="list-group-item">Código: <br>
		    			{{ lanza.codigo }}</li>
		    		<li class="list-group-item">Modelo: <br>
		    			{{ lanza.modelo }}</li>
		    		<li class="list-group-item">Serie: <br>
		    			{{ lanza.numero_serie }}</li>
		    		{% endfor %}
		  		</ul>
		  		<div class="card-body">
		    		<a href="{% url 'app:registros' %}" class="card-link">Registros</a>
		  		</div>
			</div>
		</div>
	</div>
</div>
<br>
{% if pilas %}
<h3><b>Pilas</b></h3>
<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Nombre</th>
      <th scope="col">Predio</th>
      <th scope="col">Fecha creación</th>
      <th scope="col">Estado</th>
      <th scope="col">Acción</th>
    </tr>
  </thead>
  <tbody>
  	{% for pila in pilas %}
	    <tr>
	      <th scope="row">{{forloop.counter}}</th>
	      <th>{{pila.nombreID}}</th>
	      <td>{{pila.predio}}</td>
	      <td>{{pila.fecha_creacion|date:"d-m-Y"}}</td>
	      <td>{{pila.estado_actual}}</td>
	      <th>
	      	{#<a class="btn btn-warning btn-sm" href="{% url 'app:pila-update' pila.id %}" role="button">Editar</a>#}
	      	<a class="btn btn-primary btn-sm" href="{% url 'app:mediciones-pila' pila.id %}" role="button">Ver Detalle</a>
	      	{#<a class="btn btn-danger btn-sm" href="{% url 'app:pila-delete' pila.id %}" role="button">Eliminar</a>#}
	      </th>
	    </tr>
    {% endfor %}
  </tbody>
</table>
{% else %}
<h4>No existen pilas registradas</h4>
{% endif %}
<!--
<a class="btn btn-primary" href="{% url 'app:pila-nueva' %}" role="button">Agregar Pila</a>
<a class="btn btn-primary" href="{% url 'app:predio-nuevo' %}" role="button">Agregar predio</a>
<a class="btn btn-primary" href="{% url 'app:materia-prima-nueva' %}" role="button">Agregar Materia Prima</a>
-->
{% endblock %}

app/templates/app/materiaprima_form.html
{% extends 'base_generic.html' %}

{% block title %}
	Agregar Materia Prima
{% endblock %}

{% block page_content %}
<br>
<h3>Agregar Materia Prima</h3>
<div class="container">
	<form method="POST" enctype="multipart/form-data"> 
	    <!-- Security token -->
	    {% csrf_token %} 

	    {% for field in form %}
	    <div class="form-group">
		    <label for="{{ field.name }}">{{ field.label }}</label>
		    {{ field }}
	  	</div>
	  	{% endfor %}
	  	<br>
	  <input type="submit" class="btn btn-primary" value="Guardar">
	</form>
</div> 
{% endblock %}

app/templates/app/mediciones_pila.html
{% extends "base_generic.html" %}

{% block title %}
	Registros
{% endblock %}

{% block page_content %}
<br>
<h3>Registros para Pila {{ pila.nombreID }}</h3>


<table class="table">
  <tbody>
    <tr>
      <td>
        {% if pila.posicion %}
        <b>Posición:</b> {{ pila.posicion }}<br>
        {% endif%}
        <b>Predio:</b> {{ pila.predio }} <br>
        <b>Estado:</b> {{ pila.estado_actual }}
      </td>
      {% if foto %}
        <td>
          <img src="{{ foto.url }}" alt="foto-pila" width="300" height="200"> 
        </td>
      {% else %}
        <td>
          <p>Sin imagen</p>
        </td>
      {% endif %}
    </tr>
  </tbody>
</table>

{% if materia_prima %}
<br>
<h4> Materias Primas </h4>

<table class="table table-borderless">
    <thead>
      <tr>
        <th scope="col">Nombre</th>
        <th scope="col">Cantidad</th>
        <th scope="col">Unidad medida</th>
      </tr>
    </thead>
    <tbody>
        {% for materia in materia_prima %}
          <tr>
            <td>{{ materia.nombre }}</td>
            <td>{{materia.cantidad}}</td>
            <td>{{materia.unidad_medida}}</td>
          </tr>
      {% endfor %}
    </tbody>
  </table>
{% else %}
<div class="alert alert-warning" role="alert">
        No existen registros de materias primas para pila {{pila.nombreID}}
    </div>
{% endif %}
{% if registros %}
<br>
<h4> Mediciones </h4>

<table class="table table-hover">
    <thead>
      <tr>
        <th scope="col">Día</th>
        <th scope="col">Fecha</th>
        <th scope="col">Temperatura</th>
        <th scope="col">Humedad</th>
      </tr>
    </thead>
    <tbody>
        {% for medicion in registros %}
          <tr>
            <td>{{forloop.counter}}</td>
            <td>{{ medicion.fecha_creacion|date:'d/m/Y' }}</td>
            <td>{{medicion.temperatura}}</td>
            <td>{{medicion.humedad}}</td>
          </tr>
      {% endfor %}
    </tbody>
  </table>

  <a class="btn btn-primary" href="{% url 'app:chart' pila.id %}" role="button">Ver gráfico</a>
  <a class="btn btn-primary" href="https://www.google.cl/maps/@-36.8174503,-73.0423481,14.21z" role="button">Ver Mapa</a>
  <a class="btn btn-primary" href="{% url 'app:pdf' pila.id %}" role="button">Reporte</a>
{% else %}
    <div class="alert alert-warning" role="alert">
        No existen mediciones para pila {{pila.nombreID}}
    </div>
{% endif %}

{% endblock %}

app/templates/app/pila_confirm_delete.html
{% extends 'base_generic.html' %}

{% block title %}
	Eliminar Pila
{% endblock %}

{% block page_content %}
<br>
<form method="post">
	{% csrf_token %}
	<div class="alert alert-danger" role="alert">
  		Vas a eliminar Pila "{{ object }}"
	</div>
    <p>¿estás seguro?</p>

    <input class="btn btn-danger btn-sm" type="submit" value="Confirmar">
</form>
{% endblock %}

app/templates/app/pila_form.html
{% extends 'base_generic.html' %}

{% block title %}
	Crear Pila
{% endblock %}

{% block page_content %}
<br>
<h3>Pila nueva</h3>
<div class="container">
	<form method="POST" enctype="multipart/form-data"> 
	    <!-- Security token -->
	    {% csrf_token %} 

	    {% for field in form %}
	    <div class="form-group">
		    <label for="{{ field.name }}">{{ field.label }}</label>
		    {{ field }}
	  	</div>
	  	{% endfor %}
	  	<br>
	  <input type="submit" class="btn btn-primary" value="Guardar">
	</form>
</div> 
{% endblock %}

app/templates/app/pila_update.html
{% extends 'base_generic.html' %}

{% block title %}
	Editar Pila
{% endblock %}

{% block page_content %}
<br>
<h3>Editar Pila</h3>
<div class="container">
	<form method="POST" enctype="multipart/form-data"> 
	    <!-- Security token -->
	    {% csrf_token %} 

	    {% for field in form %}
	    <div class="form-group">
		    <label for="{{ field.name }}">{{ field.label }}</label>
		    {{ field }}
	  	</div>
	  	{% endfor %}
	  	<br>
        <div class="container">
			<input type="submit" class="btn btn-primary" value="Guardar">
		</div>
	</form>
</div> 
{% endblock %}

app/templates/app/predio_form.html
{% extends 'base_generic.html' %}

{% block title %}
	Agregar Predio
{% endblock %}

{% block page_content %}
<br>
<h3>Agregar predio</h3>
<div class="container">
	<form method="POST" enctype="multipart/form-data"> 
	    <!-- Security token -->
	    {% csrf_token %} 

	    {% for field in form %}
	    <div class="form-group">
		    <label for="{{ field.name }}">{{ field.label }}</label>
		    {{ field }}
	  	</div>
	  	{% endfor %}
	  	<br>
	  <input type="submit" class="btn btn-primary" value="Guardar">
	</form>
</div> 
{% endblock %}

app/templates/app/registros.html
{% extends "base_generic.html" %}

{% block title %}
	Registros
{% endblock %}

{% block page_content %}
<br>
<h3><b>Registros</b></h3>
{{ now }}
{% if mediciones %}
{% for pila in pilas %}
<h4>Pila {{ pila.nombreID }}</h4>
<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">Fecha</th>
      <th scope="col">Temperatura</th>
      <th scope="col">Humedad</th>
    </tr>
  </thead>
  <tbody>
  	{% for medicion in mediciones %}
  		{% if medicion.pila == pila %}
	    <tr>
	      <td>{{ medicion.fecha_creacion|date:'d/m/Y' }}</td>
	      <td>{{medicion.temperatura}}</td>
	      <td>{{medicion.humedad}}</td>
	    </tr>
	    {% endif %}
	{% endfor %}
  </tbody>
</table>

{% endfor %}
{% else %}
<h4 style="color: red;">No existen datos</h4>

{% endif %}

{% endblock %}